package me.slavita.construction.common.utils

const val LOADING_STATE_CHANNEL = "loading:finish"
const val STRUCTURE_BLOCK_CHANNEL = "structure:currentBlock"
const val STRUCTURE_PLACE_CHANNEL = "structure:place"
const val STRUCTURE_HIDE_CHANNEL = "structure:hide"
const val STORAGE_INIT_CHANNEL = "storage:initialize"
const val STORAGE_SHOW_CHANNEL = "storage:show"
const val STORAGE_HIDE_CHANNEL = "storage:hide"
const val SHOWCASE_INIT_CHANNEL = "showcase:initialize"
const val BANK_OPEN_CHANNEL = "bank:open"
const val BANK_SUBMIT_CHANNEL = "bank:submit"
const val FUNC_REWARD_CLICK = "func:reward:click"
const val CREATE_BORDER_CHANNEL = "border:new"
const val CHANGE_BORDER_CHANNEL = "border:change"
const val DELETE_BORDER_CHANNEL = "border:delete"
