boards:
  1:
    title: "Топ\nпо §bОпыту"
    value: "Опыт"
    color: "§b"
  2:
    title: "Топ\n§2Глобальных бустеров"
    value: "Бустеров"
    color: "§2"
  3:
    title: "Топ\nпо §eПроектам"
    value: "Проектов"
    color: "§e"
  4:
    title: "Топ\nпо §aПрибыли"
    value: "Доход"
    color: "§a"
  5:
    title: "Топ\nпо §6Монетам"
    value: "Доход"
    color: "§6"
  6:
    title: "Топ\n§dПерерождений"
    value: "Перерождений"
    color: "§d"
