boards:
  1:
    title: "Топ\nпо опыту"
    value: "Опыт"
  2:
    title: "Топ\nГлобальных бустеров"
    value: "Бустеров"
  3:
    title: "Топ\nпо проектам"
    value: "Проектов"
  4:
    title: "Топ\nпо доходу"
    value: "Доход"
  5:
    title: "Топ\nпо доходу"
    value: "Доход"
  6:
    title: "Топ\nПерерождений"
    value: "Перерождений"
