boards:
  1:
    title: "Топ\n§fпо §bОпыту"
    value: "Опыт"
    color: "§b"
    field: "statistics.experience"
    fieldSize: "70.0"
    formatter: "MoneyFormatter"
  2:
    title: "Топ\n§2Глобальных бустеров"
    value: "Бустеров"
    color: "§2"
    field: "statistics.money"
    fieldSize: "60.0"
    formatter: "ExpFormatter"
  3:
    title: "Топ\n§fпо §eПроектам"
    value: "Проектов"
    color: "§e"
    field: "statistics.money"
    fieldSize: "60.0"
    formatter: "ReputationFormatter"
  4:
    title: "Топ\n§fпо §aПрибыли"
    value: "Доход"
    color: "§a"
    field: "statistics.money"
    fieldSize: "80.0"
    formatter: "MoneyFormatter"
  5:
    title: "Топ\n§fпо §6Монетам"
    value: "Монет"
    color: "§6"
    field: "statistics.money"
    fieldSize: "80.0"
    formatter: "MoneyFormatter"
  6:
    title: "Топ\n§fпо §dРепутации"
    value: "Репутации"
    color: "§d"
    field: "statistics.reputation"
    fieldSize: "70.0"
    formatter: "ReputationFormatter"
