command-key: "e7c73529bb9e2ced61424b792f10019f"
dialogs:
  1:
    title: "Обучение"
    action: "CONTINUE"
    content:
      - "Здравствуйте наш уважаемый мэр"
  2:
    title: "Обучение"
    action: "CONTINUE"
    content:
      - "Здесь находится ваш город, но в нём не хватает зданий"
      - "Ваша цель - застроить его и разбогатеть"
  3:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "В начале вам нужно начать строить первое здание самому"
  3-not_complete:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Вы не начали строить здание"
  4:
    title: "Обучение"
    action: "CONTINUE"
    content:
      - "Отлично, для строительства вам нужны блоки"
      - "Держите, этого хватит на первое время"
      - "После вам нужно будет покупать блоки в магазине"
  5:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "С помощью полученных блоков постройте ваше первое здание"
  5-not_complete:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Вы ещё не достроили первое здание"
  6:
    title: "Обучение"
    action: "CONTINUE"
    content:
      - "Отлично, вы справились"
  7:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "У вас появились первые деньги. Теперь вы можете нанимать рабочих"
      - "Наймите 1 рабочего и возвращайтесь сюда"
  7-not_complete:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Вы не наняли ни одного рабочего"
  8:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Теперь начните строить здание, используя купленного рабочего"
  8-not_complete:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Вы не начали строить здание, используя рабочего"
  9:
    title: "Обучение"
    action: "CLOSE"
    content:
      - "Отлично! Пока вы будете играть, ваши рабочие будут строить новые здания."
      - "В конце постройки вам нужно будет собрать награду за постройку. Удачи!"