npc:
  - title: "Покупка работников"
    labelTag: "1"
    skinType: "uuid"
    skin: "e2543a0a-5799-11e9-8374-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "BuyLootboxMenu"
  - title: "Работники"
    labelTag: "2"
    skinType: "uuid"
    skin: "307264a1-2c69-11e8-b5ea-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "WorkerTeamMenu"
  - title: "Склад"
    labelTag: "3"
    skinType: "uuid"
    skin: "303c31eb-2c69-11e8-b5ea-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "StorageMenu"
  - title: "Активные проекты"
    labelTag: "4"
    skinType: "uuid"
    skin: "ba821208-6b64-11e9-8374-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "ActiveProjectsMenu"
  - title: "Банк"
    labelTag: "5"
    skinType: "uuid"
    skin: "ba821208-6b64-11e9-8374-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "BankMainMenu"
  - title: "Старина Джо"
    labelTag: "guide"
    skinType: "uuid"
    skin: "6326e7a1-8dd1-11e9-80c4-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "GuideDialog"
