npc:
  - title: "§aРаботники"
    labelTag: "2"
    skinType: "uuid"
    skin: "307264a1-2c69-11e8-b5ea-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "WorkerMenu"
    banner:
      height: 16
      weight: 42
      offset: 3.5
      content: "§aУправление\n§aРаботниками"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§aСклад"
    labelTag: "3"
    skinType: "uuid"
    skin: "303c31eb-2c69-11e8-b5ea-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "StorageMenu"
    banner:
      height: 16
      weight: 42
      offset: 3.5
      content: "§aХранение\n§aБлоков"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§bАктивные проекты"
    labelTag: "4"
    skinType: "uuid"
    skin: "ba821208-6b64-11e9-8374-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "ActiveProjectsMenu"
    banner:
      height: 16
      weight: 42
      offset: 3.5
      content: "§bСписок\n§bПроектов"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§6Банкир"
    labelTag: "5"
    skinType: "uuid"
    skin: "ba821208-6b64-11e9-8374-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "BankMainMenu"
    banner:
      height: 8
      weight: 42
      offset: 3.0
      content: "§6Банк"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§aСтарина Джо"
    labelTag: "guide"
    skinType: "uuid"
    skin: "6326e7a1-8dd1-11e9-80c4-1cb72caa35fd"
    itemKey: "other"
    itemValue: "stats"
    action: "GuideDialog"
    banner:
      height: 8
      weight: 42
      offset: 3.0
      content: "§a§lОбучение"
      carve-size: 1.0
      lines-size:
        - 0.5
