npc:
  - title: "§aРаботники"
    labelTag: "1"
    skinType: "url"
    skin: "workers.png"
    itemKey: "other"
    itemValue: "myfriends"
    action: "WorkerMenu"
    banner:
      height: 16
      weight: 42
      offset: 3.0
      content: "§aУправление\n§aРаботниками"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§aЕжедневные награды"
    labelTag: "2"
    skinType: "url"
    skin: "daily.png"
    itemKey: "other"
    itemValue: "quests"
    action: "DailyMenu"
    banner:
      height: 16
      weight: 42
      offset: 3.0
      content: "§aЕжедневные\n§aНаграды"
      carve-size: 2.0
      lines-size:
        - 0.5
        - 0.5
  - title: "§aПроводник"
    labelTag: "3"
    skinType: "url"
    skin: "locations.png"
    itemKey: "alpha"
    itemValue: "islands"
    action: "LocationsMenu"
    banner:
      height: 8
      weight: 42
      offset: 2.5
      content: "§6Локации"
      carve-size: 2.0
      lines-size:
        - 0.5
  - title: "§bАктивные проекты"
    labelTag: "4"
    skinType: "url"
    skin: "projects.png"
    itemKey: "other"
    itemValue: "book"
    action: "ActiveProjectsMenu"
    banner:
      height: 8
      weight: 42
      offset: 2.5
      content: "§6Проекты"
      carve-size: 2.0
      lines-size:
        - 0.5
  - title: "§6Банкир"
    labelTag: "5"
    skinType: "url"
    skin: "banker.png"
    itemKey: "other"
    itemValue: "coin3"
    action: "BankMainMenu"
    banner:
      height: 8
      weight: 42
      offset: 2.5
      content: "§6Банк"
      carve-size: 2.0
      lines-size:
        - 0.5
  - title: "§aСтарина Джо"
    labelTag: "guide"
    skinType: "url"
    skin: "guide.png"
    itemKey: "other"
    itemValue: "search"
    action: "GuideDialog"
    banner:
      height: 8
      weight: 42
      offset: 2.6
      content: "§a§lОбучение"
      carve-size: 1.0
      lines-size:
        - 0.5
