showcases:
  1:
    title: 'Магазин "Напильник"'
  2:
    title: 'Магазин "МастерОК"'
  3:
    title: 'Магазин "Стружка"'
  4:
    title: 'Магазин "Кран"'
  5:
    title: 'Магазин "Пила"'
  6:
    title: 'Магазин "Грузовой"'