showcases:
  - id: 1
    title: 'Магазин "Напильник"'
  - id: 2
    title: 'Магазин "МастерОК"'
  - id: 3
    title: 'Магазин "Стружка"'
  - id: 4
    title: 'Магазин "Кран"'
  - id: 5
    title: 'Магазин "Пила"'
  - id: 6
    title: 'Магазин "Грузовой"'