rarity:
  common:
    title: "§aОбычный"
    price: 100
  rare:
    title: "§aРедкий"
    price: 10000
  epic:
    title: "§aЭпический"
    price: 1000000
  legendary:
    title: "§aЛегендарный"
    price: 100000000
rapacity:
  - title: "§aНизкая"
    value: 1.0
    reliabilityMin: 10
    reliabilityMax: 50
  - title: "§aСредняя"
    value: 1.0
    reliabilityMin: 50
    reliabilityMax: 80
  - title: "§aВысокая"
    value: 1.0
    reliabilityMin: 80
    reliabilityMax: 100